"""add count column to association table

Revision ID: fb3c7645af65
Revises: 7e27cbd3d141
Create Date: 2025-02-13 00:58:20.649873

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fb3c7645af65"
down_revision: Union[str, None] = "7e27cbd3d141"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_item_association",
        sa.Column("count", sa.Integer(), server_default="1", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_item_association", "count")
    # ### end Alembic commands ###
